### PR TITLE
Clarification of stop_times.stop_id

### PR DESCRIPTION
**Pull request by timMillet**
Following demand in the issue https://github.com/google/transit/issues/257:

This pull request clarifies the definition of the fields `stop_times.stop_id`.
- Explicitly tells that the referenced locations must have `stops.location_type` values of `0` or empty.
- Future-proof phrasing: it references only what must be done.

### CODE REVIEW

**Comment by mmorang** [comment]
Thanks, @timMillet. This looks good to me and is consistent with my understanding of the specification.

**Comment by skinkie** [comment]
I am impatient to vote. Go Go Go! (OpenGeo)

**Comment by timMillet** [comment]
@skinkie I'd tend to think that this change is editorial only, and would not require a vote. Do you think this change is worth a vote on your side?

**Comment by skinkie** [comment]
No, I think this just makes things more clear.

**Comment by timMillet** [comment]
Ok, thanks. I'll merge!

**Pull request merged**
