### PR TITLE
Amend articles 7.4-8 of the Specification Amendment Process

### PR DESCRIPTION
**Pull request by scmcca**
Hi GTFS community,

As consulted in #262, articles 7.4-8 of the [Specification Amendment Process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md) for both GTFS Schedule and GTFS Realtime are not always followed. They state that:

> **7.4:** If the advocate continues the work on proposal then a new vote can be called for at any point in time but no later than 30 calendar days after the end of the previous vote.<br>
**7.5:** If a vote was not called within 30 calendar days from the original proposal or 30 calendar days since end of the previous vote, then the proposal is abandoned.<br>
 **8:** If the proposal is abandoned, the corresponding pull request is closed.
 
In practice, PRs almost always remain open well after the 30-day allowance or have otherwise been left inactive. This has led to noise in the repository and scatters focus on decision-making and participation. At the same time, it is often useful for the development and discussion of a given proposal to last longer than the prescribed 30-days. 

This proposal aims to: 
1. Bring the rules in alignment with the current practice. 
2. Have a changes process that is followed and respected throughout (and not only the pieces that are convenient).
3. Bring focus to relevant discussions.
4. Encode rules for clearing out stale PRs.
5. Establish a pace of decision-making in the community.

The proposal accomplishes this by allowing PRs to remain open for as long as relevant with the expectation that the PR will be closed after 30 days of inactivity (i.e., no new commits, no new comments). The advocate may renew the conversation at any time after it has been closed. 

We can discuss adjusting the amount of time to be shorter or longer (i.e., 60, 90 days).

Please see the "Files changed" tab for the changes. I have proposed the changes as separate commits for GTFS Schedule and GTFS Realtime to ease the review, though the changes to either file are equivalent. As this is a change that requires alignment in the community, we will use the current Specification Amendment Process to guide the proposal.

Please review and leave any actionable feedback! Thanks.

### CODE REVIEW

**Comment by brodyFlannigan** [comment]
Everything makes sense. Looks good to me.

**Comment by skinkie** [comment]
Looks good.

**Comment by barbeau** [comment]
Looks good! I also propose that we enforce this with a Stale bot - https://github.com/apps/stale.

**Comment by skinkie** [comment]
> I also propose that we enforce this with a Stale bot - https://github.com/apps/stale.

Having seen this in other projects, I notice that applying this to "issues" is _very_ annoying, so only for pull requests then.

**Comment by scmcca** [comment]
@skinkie I agree. I think the rules proposed here should apply only to PRs. "Stale" issues are less of a problem IMHO since there are no conflicts with how long an issue can be open with the current Specification Amendment Process. Those would have to be moderated based on whether they have been addressed or are relevant.

@barbeau I would love to see this automated with a stale bot. With that in mind, we should get specific about how many days since last activity it would issue a warning, and at how many days it would close the PR. 

@ all, Any thoughts on what could be a reasonable timelines for automated warning and closing?

**Comment by barbeau** [comment]
>Any thoughts on what could be a reasonable timelines for automated warning and closing?

Per the proposed language in this PR the close threshold is 30 days, so maybe a warning halfway at 15 days?

**Review by timMillet — APPROVED** [review]
LGTM!

**Comment by scmcca** [comment]
There have been at least 7 days since this PR was opened, and the conversation seems to be stable. Thanks to everyone who provided feedback. Any remaining feedback is welcomed. As per the [Specification Amendment Process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md), we can call a vote!

I hereby call a vote to amend articles 7.4-8 of the specification amendment processes as outlined in this PR. Voting will end on 2021-06-15 at 23:59:59 UTC.

**Comment by brodyFlannigan** [comment]
**+1** Brody Flannigan Transit Data

**Comment by barbeau** [comment]
+1 USF

**Comment by e-lo** [comment]
+1 Cal-ITP

**Comment by flocsy** [comment]
+1 (as for the warning I think it should be closer to the end, something like 5 days or 1 week before closing it)

**Comment by scmcca** [comment]
Voting has to come to an end. We have 4 votes in favor and 0 votes opposed. As per the Specification Amendment Process, I'm pleased to announce that this PR is accepted. Thanks to everyone involved!

**Pull request merged**
