### PR TITLE
Fix #102 - Add StopTimeUpdate.ScheduleRelationship UNSCHEDULED value

### LINKED ISSUE #102: Add "UNSCHEDULED" value for StopTimeUpdate.ScheduleRelationship for frequency exact_times=0 trips
Currently, [TripDescriptor.ScheduleRelationship](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-schedulerelationship-1) has an enum value of `UNSCHEDULED`, which is defined as:

>A trip that is running with no schedule associated to it - this value is used to identify trips defined in GTFS frequencies.txt with exact_times = 0. It should not be used to describe trips not defined in GTFS frequencies.txt, or trips in GTFS frequencies.txt with exact_times = 1.

However, it's not clear what cooresponding enum value should be used for exact_times=0 trips for [StopTimeUpdate.ScheduleRelationship](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-schedulerelationship), as it doesn't have an `UNSCHEDULED` value.

As a result, you could potentially have a feed that looks like this, which is not clearly labeled as incorrect in the current spec:

~~~
entity {
  id: "1121"
  trip_update {
    trip {
      trip_id: "5"
      start_time: "19:29:28"
      start_date: "20180910"
      schedule_relationship: UNSCHEDULED
      route_id: "C"
    }
    stop_time_update {
      stop_sequence: 1
      arrival {
        time: 1536609516
      }
      stop_id: "421"
      schedule_relationship: SCHEDULED
    }
    stop_time_update {
      stop_sequence: 2
      arrival {
        time: 1536609552
      }
      stop_id: "425"
      schedule_relationship: SCHEDULED
    }
~~~

Furthermore, because `SCHEDULED` is the default value if `schedule_relationship` is left empty, we need a separate enum value to represent exact_times=0 trips.

Therefore, I believe an `UNSCHEDULED` enum value should be added to StopTimeUpdate.ScheduleRelationship to fix this, with a definition of:

>The vehicle is proceeding in accordance with the order of stops defined in GTFS stop_times.txt for a trip with frequencies.txt exact_times = 0 or empty. It should not be used to describe a stop on a trip not defined in GTFS frequencies.txt, or for a stop on a trip in GTFS frequencies.txt with exact_times = 1.

### PR DESCRIPTION
**Pull request by barbeau**
Currently, [TripDescriptor.ScheduleRelationship](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-schedulerelationship-1) has an enum value of `UNSCHEDULED`, which is defined as:

>A trip that is running with no schedule associated to it - this value is used to identify trips defined in GTFS frequencies.txt with exact_times = 0. It should not be used to describe trips not defined in GTFS frequencies.txt, or trips in GTFS frequencies.txt with exact_times = 1.

However, there currently is no corresponding value for exact_times=0 trips for [StopTimeUpdate.ScheduleRelationship](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-schedulerelationship), as it doesn't have an `UNSCHEDULED` value.

As a result, you could have a feed that looks like this, which is incorrect:

~~~
entity {
  id: "1121"
  trip_update {
    trip {
      trip_id: "5"
      start_time: "19:29:28"
      start_date: "20180910"
      schedule_relationship: UNSCHEDULED
      route_id: "C"
    }
    stop_time_update {
      stop_sequence: 1
      arrival {
        time: 1536609516
      }
      stop_id: "421"
      schedule_relationship: SCHEDULED
    }
    stop_time_update {
      stop_sequence: 2
      arrival {
        time: 1536609552
      }
      stop_id: "425"
      schedule_relationship: SCHEDULED
    }
~~~

Even worse, because `SCHEDULED` is the default value if `schedule_relationship` is not populated, the `schedule_relationship: SCHEDULED` is actually implied if we don't provide a separate enum value to represent exact_times=0 trips.

As a result, currently it isn't possible to correctly represent `stop_time_updates` for exact_times=0 trips.

This proposal adds a StopTimeUpdate.ScheduleRelationship `UNSCHEDULED` value so that exact_times=0 trip `stop_time_updates` can be correctly labeled.

Announced on the GTFS-realtime Google Group at https://groups.google.com/forum/#!topic/gtfs-realtime/qDVethThcQc.

### CODE REVIEW

**Comment by barbeau** [comment]
This pull request has been open for more than one week, so per the Official Process I'm calling for a vote.  To clarify, I'm proposing that this be added as an experimental field value.

Vote will be closed on Monday August 5th at 23:59:59 UTC.

**Comment by harringtonp** [comment]
Makes sense, +1

**Comment by gcamp** [comment]
+1

**Comment by abyrd** [comment]
There may be some implications to this I'm not thinking of, but based on a read-through of this issue it looks like a good idea to me. Since this is considered an experimental value, leaving time for any unexpected consequences or revisions to emerge, I'm +1.

**Comment by barbeau** [comment]
The vote on this issue is closed with the following results:
* Yes - 3
* No - 0
* Abstain - 0

So it passes!  Thanks all!

**Pull request merged**
