### PR TITLE
GTFS-Flex [Voting ver.]

### PR DESCRIPTION
**Pull request by tzujenchanmbd**
### Context

This PR is the "voting version" of [PR#388](https://github.com/google/transit/pull/388), with changes that align completely with the changes up to PR#388. The only difference is that this PR is based on the current spec, while PR#388 is based on the spec from July last year.

The Flex specification proposal is about to enter the voting stage. Due to numerous spec changes since last July, PR#388 has many conflicts with the current spec. To avoid unexpected changes to the current spec during conflict resolution, we have decided to open a new PR.

After this PR is opened, all potential future changes will occur here, and PR#388 will not have any updates. PR#388 will be temporarily kept for contextual reference and will be closed afterward. For details on all previous discussions, please refer to [PR#388](https://github.com/google/transit/pull/388) and the [working group meeting notes](https://docs.google.com/document/d/1ap7gXjCOa2pF1-sK8LonyNH-VO668Mq-vZAIR_Adhy4/edit#heading=h.hmvo53ak6eh6).

Additionally, we have created a [data example page](https://github.com/MobilityData/gtfs.org/pull/301) in the MobilityData/gtfs.org repo to help better understand this proposal. We plan to publish these data examples on gtfs.org once this proposal pass the vote. Some descriptions in this spec proposal will directly link to this data example page on gtfs.org.

Below is an overview of this GTFS-Flex proposal:
<hr>

### The changes in this PR are:

- Modify file:
  - Modify `stop_times.txt` to clarify elements of the current specification necessary to inform data consumers of how to interpret the added and extended files and fields.
  - Modify `stops.stop_id` to ensure unique ID across all `stops.stop_id`, locations.geojson `id`, and `location_group_id` values.
- Extend file:
  - Extend `stop_times.txt` with `location_group_id` and `location_id` to allow trips referencing location group and/or GeoJSON location in dedicated fields.
  - Extend `stop_times.txt` with `start_pickup_drop_off_window` and `end_pickup_drop_off_window` to define the time that demand responsive transportation service becomes available/ends in a GeoJSON location, location group, or stop.
  - Extend `stop_times.txt` with `pickup_booking_rule_id` and `drop_off_booking_rule_id` to define links to booking rules.
- Add new file:
  - `location_groups.txt` & `location_group_stops.txt` to allow grouping of stops which allow predetermined groups of these features to be specified on individual rows of `stop_times.txt`.
  - `locations.geojson`, to define zones (`Polygon` or `Multipolygon`) where riders can request either pickup or drop off.
  - `booking_rules.txt`, to define the booking rules that provide riders information about how to request service.
<hr>

Please help review this PR. Support resources from first adopters for voting will be released later.

### CODE REVIEW

**Comment by tzujenchanmbd** [comment]
Hello everyone,

Support resources from first adopters are ready.
- We have one producer: [Trillium](https://trilliumtransit.com/)
- We have two consumers: [Transit](https://transitapp.com/), [Open Trip Planner](https://www.opentripplanner.org/)

Please refer to this [adoption tracker](https://gtfs.org/extensions/flex/#adoption-tracker) for the fields adopted by each organization.

As per the [GTFS Amendment process](https://gtfs.org/schedule/process/#specification-amendment-process), the requirements to open a vote are met. We are opening a vote for adding GTFS-Flex.

Voting ends on 2024-03-18 at 23:59:59 UTC.
<hr>

Trillium's example datasets for Brown County and Otter Express in Minnesota, US:
https://data.trilliumtransit.com/gtfs/browncounty-mn-us/browncounty-mn-us--flex-v2.zip
https://data.trilliumtransit.com/gtfs/otterexpress-mn-us/otterexpress-mn-us--flex-v2.zip 

Transit App's implementation:
- Service options:


- Deviated route:


- On-demand service with zone:


It is possible to reproduce more examples in the regions directly on Transit App.
<hr>

Trillium's example dataset for Island Transit in Washington, US:
https://data.trilliumtransit.com/gtfs/islandtransit-wa-us/islandtransit-wa-us--flex-v2-TEST.zip

Open Trip Planner's implementation:
- Zone-based trip: http://tinyurl.com/233fwvj9
- Location groups trip: http://tinyurl.com/2buv2n69

**Comment by westontrillium** [comment]
+1 from Trillium

Thank you to all our partners who have worked with us over the years on implementing this powerful extension, and thank you to everyone's contributions in getting Flex where it is today. What an odyssey!

**Comment by tsherlockcraig** [comment]
+1 from WSDOT!

**Comment by frapeti** [comment]
+1 from Ualabee!

**Comment by evansiroky** [comment]
+1 Caltrans. We're excited for this to finally come to a vote!

**Comment by e-lo** [comment]
+1 UrbanLabs.  🎉 So excited to see this important extension get to this stage.

**Comment by ElliottMcfadden** [comment]
+1 Minnesota Department of Transportation. We are happy to have been part of this process.

**Comment by davidr1234** [comment]
+1 SBB SKI+

**Comment by klement-MENTZ** [comment]
+1 MENTZ GmbH

**Review by sureshgaussian — COMMENTED** [review]
+1 from Gaussian Solutions.

**Comment by gcamp** [comment]
+1 from Transit

**Comment by rbarcham** [comment]
+1 from Cambridge Systematics, very excited to move this along!

**Comment by drewda** [comment]
+1 from Interline

**Comment by uwtcat** [comment]
+1 from Taskar Center for Accessible Technology, UW

**Comment by jon-campbell-ibigroup** [comment]
+1 from Arcadis (fka IBI Group)

**Comment by SeanKCFH** [comment]
+1 from King County

**Comment by tzujenchanmbd** [comment]
The vote passed on 2024-03-19 at 23:59:59 UTC.

18 votes in favour and no votes against.

The votes came from:
OpenTripPlanner (@leonardehrenfried)
Trillium (@westontrillium)
WSDOT (@tsherlockcraig)
Ualabee (@frapeti)
Caltrans (@evansiroky)
UrbanLabs LLC (@e-lo)
Minnesota Department of Transportation (@ElliottMcfadden)
SBB SKI+ (@davidr1234)
MENTZ GmbH (@klement-MENTZ)
Gaussian Solutions (@sureshgaussian)
LA Metro (@matikin9)
Transit (@gcamp)
Cambridge Systematics (@rbarcham)
Interline (@drewda)
Taskar Center for Accessible Technology, University of Washington (@uwtcat)
Arcadis (@jon-campbell-ibigroup)
SEPTA (@nlee-septa)
King County (@SeanKCFH)

Thanks to everyone who contributed and voted!

**Comment by emmambd** [comment]
Thanks again to everyone who contributed in and voted for this 11 year effort!

MobilityData's put together [a proposal for Flex validation rules to add to the Canonical GTFS Validator](https://github.com/MobilityData/gtfs-validator/issues/1721). We intend to start with modifying pre-existing rules and including those changes in the next release in June. For those interested, please share your feedback and insights.

**Pull request merged**
