### PR TITLE
[Revision history] Move Schedule Revision history out of the spec amendment process and add the realtime revision history to this repo

### PR DESCRIPTION
**Pull request by isabelle-dr**
**Problems with the revision history**
1. the GTFS Realtime revision history is not part of this repo, although was part of the initial gtfs.org repo [to appear on gtfs.org](https://gtfs.org/realtime/process/#revision-history). Additionally, it's out of date.
2. the GTFS Schedule revision history appears [after the spec amendment process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md). 
We're reorganizing content on [gtfs.org](https://gtfs.org/) to enhance the user experience. The revision history will be placed in a new Technical Documentation section, and the Spec Amendment Process will be moved to a Community section, which will include information on how to participate. To achieve this, we need these to be two separate documents. Also, the revision history is actively maintained, while the Spec Amendment Process rarely changes, so having them in separate documents will make things clearer.

**Solution included in this PR**
- [x] Moved the GTFS Schedule revision history out of the spec amendment process in its own document
- [x] Added the GTFS Realtime revision history to this repo
- [x] Updated the GTFS Realtime revision history

This doesn't change the spec or its amendment process, so I believe a vote is not needed.

### CODE REVIEW

**Comment by niels-penneman** [comment]
This looks like a proper solution to the issue I logged earlier this month on gtfs.org (https://github.com/MobilityData/gtfs.org/issues/445).

**Review by Sergiodero — APPROVED** [review]
Thanks for working on this @isabelle-dr, Changes look good to me!

**Comment by isabelle-dr** [comment]
@niels-penneman indeed :)

**Comment by isabelle-dr** [comment]
Thanks for the review @Sergiodero! 
After a few days and a review, I am merging this PR, considering it a repo maintenance item that doesn't need a vote. 
This does not change the spec or the amendment process in any way.

**Pull request merged**
