### PR TITLE
Cleanup reference

### PR DESCRIPTION
**Pull request by polettif**
While trying to parse `reference.md` I noticed some inconsistencies in how names are used. This is just a "typo" PR which uses the same naming pattern for all fields. Please let me know if I'm missing some reason why "Required" was used as a column name instead of "Presence" for location_group and location_group_stops.

Also, the revision date (Nov 16, 2023) at the top is also not up-to-date but I refrained from changing that as well.

### CODE REVIEW

**Comment by polettif** [comment]
Ah, to be honest the CLA is too much of a hassle :) Feel free to use this info somewhere down the line.

**Comment by eliasmbd** [comment]
Hello @polettif. Thank you for bringing this up. Sorry to hear you are having issues with the CLA. I will pass this along to the team at MobilityData and we can get back to you. Do you mind if we re-open this editorial PR regardless of CLA status?

**Comment by polettif** [comment]
> I will pass this along to the team at MobilityData and we can get back to you. Do you mind if we re-open this editorial PR regardless of CLA status?

Thanks 👍 No, not at all

**Comment by tzujenchanmbd** [comment]
Closing this PR as #453 merged. 

Thanks again @polettif !

**Pull request closed without merging**
