### PR TITLE
Implement visualize_pathways.py

### PR DESCRIPTION
**Pull request by aababilov**
Generates a GraphViz DOT file that Visualizes pathway graph for a given GTFS feed.

Graph vertices are stations, platforms, entrances, generic nodes and boarding areas.
Graph edges are pathways.

Legend for vertices:
* platform: light sky blue
* station: light yellow
* entrance: light coral
* generic_node: light grey
* boarding_area: springgreen

Usage:

  $ visualize_pathways.py my-feed-dir my-feed.dot
  $ dot -T png -o my-feed.png my-feed.dot

### CODE REVIEW

**Comment by aababilov** [comment]
Here is a PNG file created for the test feed.
au-sydney-entrances

**Comment by davidlattimore** [comment]
LGTM

**Comment by skinkie** [comment]
Would it be possible to also create a map view? Analogue to https://github.com/google/transit/pull/129?

**Comment by aababilov** [comment]
Yes, this can be added as an extra feature.

**Pull request merged**
