### PR TITLE
Remove headsign preposition for consistency with Best Practices

### PR DESCRIPTION
**Pull request by antrim**
Small modification to make GTFS reference more consistent with Best Practices (http://gtfs.org/best-practices/#trips_3). Removes the preposition in the examples of destination-based headsigns.

### CODE REVIEW

**Comment by antrim** [comment]
I signed it! (Might be signed as a corporation for account @trilliumtransit.) Corp name is Trillium Solutions, Inc.

**Comment by barbeau** [comment]
LGTM

**Comment by abyrd** [comment]
+1

**Comment by RachM** [comment]
LGTM.

**Comment by RachM** [comment]
Do we need to vote on this? Or can I merge it.

**Comment by barbeau** [comment]
I view this as an editorial change to match the best practices we've already voted on, so IMHO it doesn't require another vote - you can merge.

**Pull request merged**
