### PR TITLE
Add GTFS documentation

### PR DESCRIPTION
**Pull request by barbeau**
...as discussed on the transit-developers group at https://groups.google.com/forum/#!msg/transit-developers/JdGZY5A1srE/0Iq9w8LcCwAJ.

Content is from the following URLs:

* https://developers.google.com/transit/gtfs/
* https://developers.google.com/transit/gtfs/style-guide
* https://developers.google.com/transit/community
* https://developers.google.com/transit/gtfs/reference
* https://developers.google.com/transit/gtfs/changes
* https://developers.google.com/transit/gtfs/examples/gtfs-feed
* https://developers.google.com/transit/tools

...reformatted to Markdown.

Also includes the following:
* Use same Changes process as GTFS-realtime
* Update main Readme to reflect that both GTFS and GTFS-realtime now exist in the repository.
* Update main Readme with Creative Commons and Apache licensing notes
* Update URLs that pointed to old https://code.google.com/p/googletransitdatafeed site to point to the new location on Github at https://github.com/google/transitfeed

### CODE REVIEW

**Comment by skinkie** [comment]
+1

**Comment by egorich239** [comment]
Sean,
We'll land the GTFS specification here shortly, however the terms of collaboration on github will stay the same: repository LICENSE, CONTRIBUTING.md files define them as using Apache 2.0, and it will apply to GTFS specification as well.

**Comment by barbeau** [comment]
@egorich239 Do you have an estimated timeline for adding GTFS here?  Anything I can do to help move this along?

**Comment by bboissin** [comment]
@barbeau sorry for the lack of update, it's still on my plate but I haven't been able to work on it yet. I'll be on vacation for most of Feb so expect something in March. Hope it's not too much of an inconvenience.

**Comment by barbeau** [comment]
@bboissin Ok, thanks for the update.  FYI, I converted most of the spec to markdown in https://github.com/barbeau/transit/commit/fa74442fc49518f1747aaa1a9783563ae258a1a2, in case that gives you a head start.

**Pull request closed without merging**
