### PR TITLE
Reformat GTFS reference for Markdown

### PR DESCRIPTION
**Pull request by barbeau**
* Properly format tables in Markdown
* Properly format headers in Markdown
* Bump GTFS revision history date to reflect the move to Github

### CODE REVIEW

**Comment by barbeau** [comment]
Sorry, please hold - the table of contents wasn't linked properly - I'll fix that too.

**Comment by barbeau** [comment]
Ok, should be good to go now - new commit force-pushed that includes fix to Table of Contents links.

**Comment by egorich239** [comment]
Thanks you!

**Comment by barbeau** [comment]
You're welcome!  BTW, for myself as much as others - here's the secret to the table formatting if we need to do this again.

Copy HTML tables to Google Sheets:
https://docs.google.com/spreadsheets/d/1w6KHS46evCAGUpR609w4cvuPxHz86A3sQzPrJQsqQNo/edit?usp=sharing

Then dump to Markdown via MarkdownTableMaker Sheets Add-on:
https://chrome.google.com/webstore/detail/markdowntablemaker/cofkbgfmijanlcdooemafafokhhaeold?hl=en

**Pull request merged**
