### PR TITLE
Blocks and service days - Clarify relationship of block_id & service_id

### PR DESCRIPTION
**Pull request by antrim**
It was previously unclear how a block can be defined across service days.

New/added text: "A block consists of a single trip or or many sequential trips made using the same vehicle, defined by shared service day and block_id."

Removed: "The block_id must be referenced by two or more trips in trips.txt."

Note: This proposed change introduces the term of "service day" (see https://github.com/google/transit/issues/43 for discussion).

### CODE REVIEW

**Comment by mgilligan** [comment]
+1

**Comment by barbeau** [comment]
I think this definition works.  Small typo - `of a single trip or or many` should be `of a single trip or many` (there is an extra `or`).

**Comment by antrim** [comment]
Thanks @barbeau! Fixed in f64f770

**Comment by antrim** [comment]
It looks as though there is support for this change. Let's start the 7 day voting period for this change, unless anyone has other comments. So that there are 7 full calendar days, then the vote would end on Friday, February 3 @ 23:59:59 UTC.

I’m not in love with the formatted example, but I don’t know how better to do this in markdown and in the current document structure. Therefore, I propose that we get block_id definition written into the Spec reference, and leave the door open for reformat/restructure later.

**Comment by barbeau** [comment]
+1

**Comment by LeoFR** [comment]
+1

**Comment by abyrd** [comment]
+1

**Comment by antrim** [comment]
The voting period has ended. It looks as though there is support for this change. @zhsh: Can you please merge and close? We may want to do a little formatting rearrangement (for the example table) down the line.

**Comment by barbeau** [comment]
@dbabramov Thanks for merging!  Friendly request - in the future, could you please squash commits before merging?  I think it's useful to keep a multiple-commit history in a pull request so we can track changes based on comments, but personally I'd prefer to keep the history of the `master` branch clean with one commit per proposal.  Makes it easier to track proposals and changes over time.

**Pull request merged**
