### PR TITLE
Add fare_media_type=1

### PR DESCRIPTION
**Pull request by tzujenchanmbd**
### Context
Currently the valid options of fare_media_type enum are: 0-None, 2-Physical transit card, 3-cEMV, 4-Mobile app. `fare_media_type=1` for physical paper ticket has not been adopted yet. In [PR#355](https://github.com/google/transit/pull/355), `fare_media_type=1` was reserved primarily because no producers were providing data at the time.

### Change in this PR
Add `fare_media_type=1` description in `fare_media.txt`

### Value of this change
- Showing the price for fares that are purchased on a paper ticket
- Showing what needs to be used to validate the ride (the paper ticket)

**Data consumer**: [Transit](https://transitapp.com/)
**Data producer**: [MBTA](https://www.mbta.com/), [PVTA](https://www.pvta.com/index.php)

For previous discussions, please see [issue#384](https://github.com/google/transit/issues/384), [PR#355](https://github.com/google/transit/pull/355), and [working group meeting minutes](https://docs.google.com/document/d/1d3g5bMXupdElCKrdv6rhFNN11mrQgEk-ibA7wdqVLTU/edit#heading=h.623abjei5cqb).
Please go through the change and share your thoughts here.

### CODE REVIEW

**Comment by tzujenchanmbd** [comment]
@npaun @timMillet Would you be able to share a screenshot of Transit app using this type? For example displaying the ticket name and/or if you use it to display the price.

**Comment by npaun** [comment]
+1 Transit

**Comment by doconnoronca** [comment]
+1 TransSee

**Comment by westontrillium** [comment]
+1 Trillium

**Comment by drewda** [comment]
+1 from @interline-io

Our team is currently reviewing to look for the handful of situations like this in the SF Bay Area, and will tag those as `fare_media_type=1` in the Bay Area Regional Feed in the near future.

**Comment by lhynes607** [comment]
+1 PVTA

**Comment by jfabi** [comment]
+1 from the @mbta.

**Comment by bdferris-v2** [comment]
+1 from Google

**Comment by tzujenchanmbd** [comment]
The vote passed on 2023-08-01 at 23:59:59 UTC.

7 votes in favour and no votes against.

The votes came from:
Transit (@npaun)
TransSee (@doconnoronca)
Trillium (@westontrillium)
Interline-io (@drewda)
PVTA (@lhynes607)
MBTA (@jfabi)
Google (@bdferris-v2)

Thanks to everyone who contributed and voted! We are in the process of updating the [GTFS Schedule Reference](https://gtfs.org/schedule/reference/#fare_mediatxt) page on gtfs.org.

**Pull request merged**
