### PR TITLE
Arrival and departure time best practices

### PR DESCRIPTION
**Pull request by antrim**
This is one of 5 PRs that incorporates a recommendation from the [GTFS best practices](https://gtfs.org/best-practices/).

This PR recommends including estimated arrival and departure times where possible.

Related pull requests:
- [Add best practice: stop_id is not rider facing](https://github.com/google/transit/pull/169)
- [Add best practice: In seat transfer specifics](https://github.com/google/transit/pull/168)
- [Headsign best practices](https://github.com/google/transit/pull/167)
- [Add best practices: Headsign and route name examples](https://github.com/google/transit/pull/166)

### CODE REVIEW

**Comment by antrim** [comment]
This pull request has been open for more than one week, so per the Official Process I'm calling for a vote.

Vote will be closed on Tuesday, June 25th at 23:59:59 UTC.

**Comment by abyrd** [comment]
+1

**Comment by TomGoBravo** [comment]
+1

**Comment by mgilligan** [comment]
+1

**Comment by paulswartz** [comment]
+1

**Comment by ibi-group-team** [comment]
+1

**Comment by harringtonp** [comment]
A question. The timepoint description is for the arrival_time field and the departure_time refers to it. However is a timepoint not really about departures, it doesn't matter if a bus arrives early at a stop once it doesn't leave before the departure time.  It is a good idea including timepoint usage description here but I would have been just inclined to mention it in the departure_time description,

**Comment by giocorti** [comment]
@harringtonp TRB gives the following definition for a time point in this [document:](http://onlinepubs.trb.org/onlinepubs/tcrp/tcrp_webdoc_6-e.pdf)

> time point – a point on a line or route for which the time that transit units (vehicles or trains) are scheduled to pass is specified; usually, the leaving time is used.

This definition seems to imply that arrival time is sometimes used for time points, so I am hesitant to remove the time point language from the `arrival_time` field.

**Comment by thomastrillium** [comment]
+1

**Comment by paulswartz** [comment]
+1

**Comment by tyleragreen** [comment]
+1

**Comment by devadvance** [comment]
+1

**Comment by antrim** [comment]
8 votes are in favor, including at least one consumer and producer. 0 votes against. The vote passes.

**Pull request merged**
