### PR TITLE
Update proto doc link

### PR DESCRIPTION
**Pull request by gcamp**
The link to the protobuf doc changed. It was still working but the `#scalar` position on the page was lost.

### CODE REVIEW

**Comment by paulswartz** [comment]
+1

**Comment by eliasmbd** [comment]
Are we in agreement that this is a minor change and doesn't need to go through the amendment process?

**Comment by leonardehrenfried** [comment]
At least I am.

**Comment by eliasmbd** [comment]
@gcamp Thank you for bringing this up. The PR has been merged!

**Pull request merged**
