### PR TITLE
Specify that the filename are case sensitive

### LINKED ISSUE #297: Case-sensitivity of filenames
The specifications says that the columns names are case-sensitive.

However nothing is specified for filenames. Should a `Routes.txt` be a valid file for the routes or not.

I have no strong opinion here, but I believe the specification should be explicit if can be allowed or not.

### PR DESCRIPTION
**Pull request by Tristramg**
Closes #297

### CODE REVIEW

**Comment by skinkie** [comment]
Voting ends 2021-20-27 at 23:59:59 UTC.

**Comment by skinkie** [comment]
+1 OpenGeo

**Comment by scmcca** [comment]
I'll repeat my https://github.com/google/transit/issues/297#issuecomment-997995283. Should we merge this directly with no vote since it is a minor and straightforward clarification? I'm happy to follow the process as well!

**Comment by skinkie** [comment]
> I'll repeat my [#297 (comment)](https://github.com/google/transit/issues/297#issuecomment-997995283). Should we merge this directly with no vote since it is a minor and straightforward clarification? I'm happy to follow the process as well!

I think this is an issue. @Tristramg found a producer that did not implement this "correctly" hence it is a breaking change, at least for producers. I would like to follow the voting period, so that this producer can also be informed about this issue.

**Comment by paulswartz** [comment]
+1 MBTA

**Comment by scmcca** [comment]
To be clear, according to the [specification amendment process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md#specification-amendment-process) the steps taken to call a vote so far have not been legitimate. 

If we are passing this through a vote as @skinkie has [established](https://github.com/google/transit/pull/300#issuecomment-998008131), we should do it properly. 

@Tristramg As the advocate of this PR, please read up on the [specification amendment process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md#specification-amendment-process) and follow the steps so we can proceed! Looking forward to getting this merged.

**Comment by skinkie** [comment]
+1 OpenGeo

**Comment by Tristramg** [comment]
Hello,

This PR had been announced on the mailing list for 10 days and the vote has been formally opened today and will continue until 2022-01-27 23:59:59 UTC

As the process states:

> Votes before the start of the voting period are not considered.

@botanize and @paulswartz would you mind re-casting your vote as the previous won’t be considered.

I apologize for the troubles caused by lack of rigor to follow the process.

**Comment by gcamp** [comment]
+1 Transit

**Comment by flocsy** [comment]
+1 Moovit

**Comment by abyrd** [comment]
+1 Conveyal

**Comment by botanize** [comment]
+1 Metro Transit

**Comment by paulswartz** [comment]
+1 MBTA

**Comment by mgilligan** [comment]
+1, TriMet

**Pull request merged**
