### PR TITLE
Terminology change: "service date" -> "service day"

### PR DESCRIPTION
**Pull request by antrim**
This change is to make the Specification reference more consistent with common transit terminology. See issue #43 for further discussion.

### CODE REVIEW

**Comment by antrim** [comment]
It looks as though there is support for this change (see discussion in issue #43). Let's start the 7 day voting period for this change, unless anyone has other comments. So that there are 7 full calendar days, then the vote would end on Friday, February 3 @ 23:59:59 UTC.

Note that pull request #44 (open for voting) also uses the term "service day".

**Comment by barbeau** [comment]
+1 -  can you announce on gtfs-changes and cross link both?

**Comment by RachM** [comment]
+1

**Comment by abyrd** [comment]
+1

**Comment by antrim** [comment]
The voting period has ended. It looks as though there is support for this change. @zhsh: Can you please merge and close?

**Pull request merged**
