### PR TITLE
Implement upgrade_translations.py

### PR DESCRIPTION
**Pull request by aababilov**
This script upgrades GTFS data from Google translations extension [1] to GTFS-Translations [2].

[1] http://developers.google.com/transit/gtfs/reference/gtfs-extensions#translationstxt
[2] http://bit.ly/gtfs-translations

### CODE REVIEW

**Comment by davidlattimore** [comment]
LGTM

**Comment by gcamp** [comment]
Not sure I understand why this is in the GTFS specs repo? It's also a script for something that's not part of the spec yet?

**Comment by barbeau** [comment]
@gcamp I agree - these should probably be in https://github.com/google/transitfeed instead.

**Comment by gcamp** [comment]
@barbeau Created an issue on this https://github.com/google/transit/issues/157

**Pull request merged**
