### PR TITLE
Proposal: Alert `tts_header_text`, `tts_description_text` no longer experimental

### PR DESCRIPTION
**Pull request by barbeau**
GTFS-RT Alert `tts_header_text` and `tts_description_text` have been in the spec for over a year, so I suggest removing the experimental tag.

Producer: @ibi-group-team
Consumer: Trapeze (@nathan-reynolds)

Implemented for TransLink in Vancouver

I'll leave this open for discussion for a week, and then will call a vote to officially adopt.

Posted on the GTFS-realtime Google Group at https://groups.google.com/forum/#!topic/gtfs-realtime/WwZ5I5JSsdA.

### CODE REVIEW

**Comment by barbeau** [comment]
This pull request has been open for more than one week, so per the Official Process I'm calling for a vote.

Vote will be closed on Monday July 13th at 23:59:59 UTC.

**Comment by gcamp** [comment]
+1

**Comment by ibi-group-team** [comment]
+1 IBI Group

**Comment by barbeau** [comment]
The vote is closed with the following results:
* 2 in favor
    * Transit App
    * IBI Group
* 0 against
* 0 abstain

However, we need at least 3 in favor votes for this to pass.  I'd like to restart the vote to see if we can get at least 1 more in favor vote. Vote will be closed on Wednesday July 22nd at 23:59:59 UTC.

**Comment by ritesh-warade-ibigroup** [comment]
+1 IBI Group

**Comment by gcamp** [comment]
+1 Transit App

**Comment by Bertware** [comment]
+1 Trafiklab

**Comment by mgilligan** [comment]
+1 TriMet

**Pull request merged**
