### PR TITLE
Clarify when frequency-based service begins (@ vehicle departure)

### PR DESCRIPTION
**Pull request by antrim**
For frequency-based trips, does "service begin" when the vehicle arrives or departs the first stop? The amendment clarifies this  ambiguity in the Spec.Following @abyrd's suggestion and Bing and Google current practice, I've proposed a change so that service begins when the vehicle departs the first stop.

Background discussion: https://groups.google.com/d/msg/gtfs-changes/Qws9hZiFzG8/Kg0Z53P0DQAJ

### CODE REVIEW

**Comment by antrim** [comment]
For frequency-based trips, does "service begin" when the vehicle arrives or departs the first stop? The amendment clarifies this  ambiguity in the Spec.Following @abyrd's suggestion and Bing and Google current practice, I've proposed a change so that service begins when the vehicle departs the first stop.

Background discussion: https://groups.google.com/d/msg/gtfs-changes/Qws9hZiFzG8/Kg0Z53P0DQAJ

**Comment by barbeau** [comment]
I'm on-board with this.  I think the more important thing is that this is clarified in the spec and no longer ambiguous.

**Comment by antrim** [comment]
It looks as though there is support for this change. Let's start the 7 day voting period for this change, unless anyone has other comments. So that there are 7 full calendar days, then the vote would end on Friday, February 3 @ 23:59:59 UTC.

**Comment by barbeau** [comment]
+1

**Comment by LeoFR** [comment]
+1

**Comment by RachM** [comment]
+1

**Comment by abyrd** [comment]
+1

**Comment by antrim** [comment]
The voting period has ended. It looks as though there is support for this change. @zhsh: Can you please merge and close?

**Pull request merged**
