### PR TITLE
Update stop_name Best Practices

### PR DESCRIPTION
**Pull request by scmcca**
As flagged in #273 and #281 by @flocsy: proposal to disambiguate `stop_name` best practices to reflect actual published naming conventions and handling translations for local/foreign riders in `translations.txt`.

### CODE REVIEW

**Comment by flocsy** [comment]
+1 Moovit

**Comment by scmcca** [comment]
Now that 7 days of discussion have passed, we can call an official vote (@mgilligan, @skinkie, @flocsy thanks for the enthusiasm, feel free to recast your votes!). This vote is for updating the `stop_name` best practices as outlined in this PR.

Voting ends on 2021-09-10 at 23:59:59 UTC.

Thanks!

**Comment by gcamp** [comment]
+1 Transit

**Comment by skinkie** [comment]
Still voting +1 (OpenGeo)!

**Comment by brodyFlannigan** [comment]
+1 Brody Flannigan Transit Data on behalf of Transcollines.

**Comment by jspetrak** [comment]
+1 from Bileto

**Comment by paulswartz** [comment]
+1 from @mbta

**Comment by mgilligan** [comment]
+1, TriMet again

**Comment by antrim** [comment]
+1 from Trillium

**Comment by flocsy** [comment]
+1 Moovit

**Comment by darylweinberg** [comment]
+1 from @CapMetroATX


Daryl 
Weinberg
Transit Systems Architect, Capital Metro
P: 512-369-6216
E: ***@***.*** | W: www.capmetro.org
A: 2910 E 5th St, Austin TX 78702
This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by Bertware** [comment]
+1 Samtrafiken/Trafiklab

**Comment by abyrd** [comment]
+1 Conveyal

**Comment by scmcca** [comment]
The vote ended on 2021-09-10 at 23:59:59 UTC with 11 votes in favor and 0 opposed. As per the Specification Amendment Process, this vote passes!

Thanks to all involved.

**Comment by doconnoronca** [comment]
Should something to mentioned about mixed case vs all caps?

**Comment by scmcca** [comment]
@doconnoronca We can add in a following sentence:

> Provide stop names in mixed case, following local conventions, as per recommendation for all rider-facing text fields.

What do you think?

**Comment by gcamp** [comment]
That mention should be general to any string, not just stop name.

**Comment by barbeau** [comment]
http://gtfs.org/best-practices/#all-files says:

>All customer-facing text strings (including stop names, route names, and headsigns) should use Mixed Case (not ALL CAPS), following local conventions for capitalization of place names on displays capable of displaying lower case characters.

**Comment by doconnoronca** [comment]
Mixed case is already mentioned elsewhere then it is not needed here.

Often stop names are the names of two cross streets. It would be beneficial if they are seperated by a consistent seperater across the whole file, whether it be " and ", " + ", "/" or whatever. Also the street the vehicle is traveling on should be first and the cross street second.

**Comment by scmcca** [comment]
@doconnoronca Would recommending a consistent separator for cross streets be at odds with:
> The `stop_name` should match the agency's rider-facing name for the location as printed on a timetable, published online, or represented on signage. 

? For example if one agency has a timetable that publishes " and " and another agency has a timetable that publishes " / ". Technically they are following the spec recommendation to match their data to their official material, albeit using different ways to describe cross streets.

**Comment by doconnoronca** [comment]
It's where one agency uses 3 or 4 different seperators in one stops.txt file.

**Comment by scmcca** [comment]
I see! Maybe something like:
> Stops named after cross streets should separate street names by a single consistent separator within stops.txt (e.g., "at", "and", "&", "/"). The first street name should be the street that the vehicle is travelling on at the time of the stop, and the second street name should be the cross street (i.e., < first street name > < separator > < second street name >).

**Comment by brodyFlannigan** [comment]
> I see! Maybe something like:
> 
> > Stops named after cross streets should separate street names by a single consistent separator within stops.txt (e.g., "at", "and", "&", "/"). The first street name should be the street that the vehicle is travelling on at the time of the stop, and the second street name should be the cross street (i.e., < first street name > < separator > < second street name >).

I love this. I've seen some feeds with 3 or even 4 different seperators and totally inconsitent stop names so this is a huge +1 for me.

**Comment by doconnoronca** [comment]
Looks good.

**Comment by flocsy** [comment]
maybe it would be wise to create a new PR for the separator discussion, as this PR's vote already finished

**Comment by scmcca** [comment]
@flocsy I agree. Please see #285.

**Pull request merged**
