### PR TITLE
Unify `agency_lang` and `feed_lang` definitions

### PR DESCRIPTION
**Pull request by LeoFrachet**
Hi GTFS community,

This pull request is the result of the short discussion we had on [Issue 95](https://github.com/google/transit/issues/95). No need to read the whole issue discussion, here is the sum up:

#### Current Issue
Current specification gives two distinct definitions for the two language fields:
- `agency_lang` allows only two-letter language codes, using [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) (e.g. "en" for English,  "es" for Spanish or "de" for German);
- `feed_lang` allows the two letter-language codes, but also more complex [language tags](https://www.w3.org/International/articles/language-tags/), using [BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag) (e.g. "en" for English, but also "en-US" for American English or "es-419" for Spanish used in Latin America).

This implies that the high-level definition of the language (with `feed_lang`) can be specific more specific than the low-level one (with `agency_lang`), which is the opposite of what could be expected.

This distinction:
- forces producers to be less specific in the `agency_lang` than in the `feed_lang`, or discourage them to be specific in the `feed_lang`,
- forces consumers to handle two different field formats for validation, without knowing how they should handle a `feed_lang` more specific than an `agency_lang` one (e.g. "en-US" as `feed_lang` but "en" as `agency_lang`). 

#### Proposal: Unify the two definitions by allowing both fields to use language tags.
- This will reduce the complexity of the specification without reducing it's precision.
- This keeps all old datasets valid, since the two-letter language codes are included in BCP 47.
- This will only require producers to simplify their code, by allowing `agency_lang` to be like `feed_lang`.
- The only non-backward compatibility part of this proposal is that `agency_lang` was loose on the capitalization (language code should always be lower case according to ISO 639-1, aka "en", but `agency_lang` was oddly also allowing upper case, aka "EN"). I suggest we do not officialy handle this case in the spec anymore. GTFS consumers will still have to allow "EN" in short term anyway, and it's a good think IMHO to suggest to agency to follow the ISO/BCP standard in the future.

Thoughts?

### CODE REVIEW

**Comment by barbeau** [comment]
+1

**Comment by skinkie** [comment]
+1 of the proposal
+2 for the effort

**Comment by gcamp** [comment]
+1

**Comment by abyrd** [comment]
+1

**Comment by LeoFrachet** [comment]
This pull request has been open one week ago. As per the Official Process, we can now open the vote on it.

@barbeau, @skinkie, @gcamp, @abyrd & @mgilligan: Please re-vote (since all +1 given before the official voting period are not counted).

Vote will be closed on Friday August 31st at 23:59:59 UTC.

**Comment by ritesh-warade-ibigroup** [comment]
+1

**Comment by gcamp** [comment]
+1

**Comment by mgilligan** [comment]
+1

**Comment by barbeau** [comment]
+1

**Comment by LeoFrachet** [comment]
Vote is closed.

In favor:
- IBI (by @ritesh-warade-ibigroup)
- Transit (by @gcamp)
- TriMet (by @mgilligan)
- CUTR at USF (by @barbeau)
- Conveyal (by @abyrd)

Against:
[nobody]

So we have:
5 votes in favor
No vote against
=> The proposal is therefore adopted.

**Comment by skinkie** [comment]
With the recent changes, is gtfs.org also updated automatically?

**Comment by LeoFrachet** [comment]
@antrim: I remember we discussed it but I don't remember the conclusion. Is it pulling from GitHub automatically? Or should we update it by hand?

**Pull request merged**
