### PR TITLE
Add best practice: In seat transfer specifics

### PR DESCRIPTION
**Pull request by antrim**
This is one of 5 PRs that incorporates a recommendation from the [GTFS best practices](https://gtfs.org/best-practices/).

This PR adds details about properly implementing in-seat transfers. 

Related pull requests:
- [Add best practice: stop_id is not rider facing](https://github.com/google/transit/pull/169)
- [Headsign best practices](https://github.com/google/transit/pull/167)
- [Add best practices: Headsign and route name examples](https://github.com/google/transit/pull/166)
- [Arrival and departure time best practices](https://github.com/google/transit/pull/165)

### CODE REVIEW

**Comment by MuckT** [comment]
https://github.com/google/transit/pull/168#issuecomment-500629619 @paulswartz

**Comment by antrim** [comment]
This pull request has been open for more than one week, so per the Official Process I'm calling for a vote.

Vote will be closed on Tuesday, June 25th at 23:59:59 UTC.

**Comment by abyrd** [comment]
It looks like this PR only adds the text "If in-seat (block) transfers are allowed between trips, then the last stop of the arriving trip must be the same as the first stop of the departing trip." It seems strange to me that this detail is the first thing mentioned for the transfer_type field, before even the values the field can take on. No new values are defined, so it's not clear how this text relates to transfer_type. There has been discussion in the past about introducing an in-seat transfer_type, was the intent to add that value in this PR?

**Comment by antrim** [comment]
@abyrd Good point. Since @MobilityData is planning to return to https://github.com/google/transit/pull/32 soon, I think you're right that we should leave this change aside for now and wait for the the changes around "transfer rules for routes and trips, and in-seat transfers". I'll close this.

**Comment by skinkie** [comment]
@antrim Addionnaly the last stop is not always the first stop. For example an exit stop is the last stop in the sequence but does not pick up new passengers, but it is still considered the same block.

**Pull request closed without merging**
