### PR TITLE
Add new optional fields for Text-to-Speech functionality in Service Alerts feed

### PR DESCRIPTION
**Pull request by ibi-group-team**
This is a proposal to add two new optional fields for text-to-speech functionality to the ServiceAlerts feed, called tts_header_text and tts_description_text of type TranslatedString.

See discussion here: https://github.com/google/transit/issues/132

Announced on the GTFS-realtime Google Groups here: https://groups.google.com/forum/#!topic/gtfs-realtime/aI7OfMycsHw

### CODE REVIEW

**Comment by ibi-group-team** [comment]
i signed it!


---

Ritesh Warade

Director, IBI Group

617.699.9544

________________________________

**Comment by farah-machlab-ibigroup** [comment]
I'm a commit author and I'm ok with my commits being contributed to this project.

**Comment by LeoFrachet** [comment]
I agree with the fields, their names and their definitions.

Two small suggestions:
1) Add the space missing in second definition: `//Text` => `// Text`
2) Maybe something (an example or a guideline) could be added to describe what they'll contain. For information in my `tts_stop_name` proposal (https://github.com/google/transit/pull/49), I was offering this kind of definition for text-to-speech field, to help the reader understand what would be the difference of content:

> * **Text-to-speech field** - The field should contain the same information than its parent field (on which it falls back if it is empty). It is aimed to be read as text-to-speech, therefore, abbreviation should be either removed ("St" should be either read as "Street" or "Saint"; "Elizabeth I" should be "Elizabeth the first") or kept to be read as it ("JFK Airport" is said abbreviated).

**Comment by ibi-group-team** [comment]
This pull request has been open for more than one week, so we are calling for a vote.

Voting will be closed on Tuesday January 29 at 23:59:59 UTC.

**Comment by abyrd** [comment]
+1

**Comment by LeoFrachet** [comment]
+1

Pinging:
- MBTA: Dave (@DaveBarker) or Paul (@paulswartz)
- Transit app: Guillaume (@gcamp) or Juan (@juanborre)
- TriMet: Frank (@fpurcell) or Mike (@mgilligan)

**Comment by gcamp** [comment]
(That was a +1)

**Comment by paulswartz** [comment]
+0. We don't have a problem with this field, but aren't likely to incorporate it into how we use Text-to-speech for alerts.

**Comment by barbeau** [comment]
@ibi-group-team One point of clarity - I believe this vote is for adopting the `tts` fields as "experimental", right?  In that case you'll need to mark it as experimental (for an example, see `OccupancyStatus` - https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-occupancystatus)

I'm +1 for adopting as experimental field.

**Comment by ibi-group-team** [comment]
Voting for this proposal is closed and the results are:
Yes: 4
No: 0

So the proposal passes! We'll get this merged.

Thank you all!

**Comment by ibi-group-team** [comment]
@google-admin @googlebot the CLA check is currently failing so this cannot be merged. @farah-machlab-ibigroup's contributions are covered under the corporate CLA for IBI Group. Can you please confirm and update the check?

**Comment by barbeau** [comment]
Thanks @ibi-group-team and all for coming to a consensus on this!

**Pull request merged**
