### PR TITLE
Fix typo: was using "pickup" instead of "drop off" and vice-versa

### PR DESCRIPTION
**Pull request by iliasbhal**
I think there is a typo. 

Screen Shot 2019-04-09 at 10 27 52 AM

### CODE REVIEW

**Comment by aababilov** [comment]
Thank you for that change.
Please fix another typo as well. Vice versa cannot be spelled as "vis-versa". It sounds as /'wike 'wersa:/ in Latin, you can use this as a hint.

**Comment by iliasbhal** [comment]
@aababilov done :)

**Comment by aababilov** [comment]
Thanks! LGTM

**Comment by barbeau** [comment]
Thanks @iliasbhal!

**Pull request merged**
