### PR TITLE
feed_info.feed_contact_email and feed_contact_url

### PR DESCRIPTION
**Pull request by antrim**
earlier discussion:
https://groups.google.com/forum/#!topic/gtfs-changes/iJkdVB1DQnM

### CODE REVIEW

**Comment by barbeau** [comment]
@antrim Do you know if we have any consumers for these fields yet?

**Comment by antrim** [comment]
Good question. There are no consuming applications that I know of. I also ran a quick search in the Transitland Datastore code (https://github.com/transitland/transitland-datastore/search?q=contact). Data in these fields may still be used by people who download the feed and open feed_info.txt. If people do that, I'd argue we could call that a consuming "application". This is likely the case with other fields in feed_info.txt.

**Comment by barbeau** [comment]
I opened an issue for adding this to OneBusAway at https://github.com/OneBusAway/onebusaway-application-modules/issues/192 - it may address a use case we were recently discussing.

**Comment by LeoFR** [comment]
+1 for those changes

**Comment by drewda** [comment]
+1 and Transitland can be a consumer: https://github.com/transitland/transitland/issues/203

**Comment by LeoFrachet** [comment]
I'm calling for the vote, since the conversation faded out, and we have the required producer & consumer:
- at least 2 producers: Trillium (@antrim) & TriMet (@mgilligan);
- at least 1 consumer: transit.land (@drewda), maybe Transit also (pinging @gcamp @lvancraen)...

Vote is closing on Wednesday, Aug 15th, at 23:59:59 UTC.

**Comment by drewda** [comment]
Transitland does consume these fields, and I'm glad to +1 again.

**Comment by barbeau** [comment]
+1 on behalf of @CUTR-at-USF

@antrim There is a merge conflict with this PR and the master branch - could you resolve this?  I'm guessing (hoping) that this doesn't alter the text of this proposal so the vote can continue.

**Comment by evantrillium** [comment]
I am working on this on behalf of @antrim to suss out what the issue is. I'll post any questions I run into here.

**Comment by mgilligan** [comment]
+1, TriMet's GTFS includes `feed_contact_url `

**Comment by gcamp** [comment]
+1 on behalf of @TransitApp

**Comment by antrim** [comment]
@evantrillium Is working to resolve the merge conflict.

**Comment by AntoineGrapperon** [comment]
+1 on behalf of INRO Software (consumer of GTFS data)

**Comment by skinkie** [comment]
@LeoFrachet Could the voting proces please be announced in the Google Group as the proces @barbeau  described before?

+1

**Comment by LeoFrachet** [comment]
@skinkie: Thanks for pointing this out! It's a good point and I'll do it in the future!

Side note (pinging @barbeau): I re-read the CHANGES.md last week before opening the vote and opening the other Pull Request, and I didn't saw this part. I saw only that we should send a message in the Google Group when an issue is open, not when the vote is opened. So if it is something that we want to add, another PR should be open to edit the CHANGES.md accordingly.

**Comment by DaveBarker** [comment]
+1

**Comment by LeoFrachet** [comment]
Vote is closed.

**In favor:**
- @trilliumtransit (by @antrim) => Doesn’t count since he is the advocate
- @transitland / @interline-io (@drewda)
- @CUTR-at-USF (by @barbeau)
- @TriMet (by @mgilligan)
- @TransitApp (by @gcamp)
- INRO Software (by @AntoineGrapperon)
- OpenOV (by @skinkie)
- MBTA (by @DaveBarker)

**Against:**
[nobody]

**So we have:**
- 3 producers: Trillium (@antrim), TriMet (@mgilligan) & MBTA (@DaveBarker);
- 1 consumer: @transitland (@drewda)
- 7 votes in favor
- No vote against

=> The proposal is therefore adopted.

=> @barbeau: Could you check that I counted the 7 days the good way? (Just to be sure…)

Then, when merging, we should also update the Revision History in CHANGES.md

**Comment by LeoFrachet** [comment]
@antrim: Could you sign the CLA so that we could merge?

**Comment by barbeau** [comment]
@LeoFrachet Dates look good to me!  I've also opened a new issue at https://github.com/google/transit/issues/96 for adding the announcement of votes on the GTFS Changes group.

**Comment by antrim** [comment]
I signed the agreement for Google Contributor License Agreement for Trillium Solutions, Inc. on 10/27/2016.

**Comment by antrim** [comment]
I signed it!

**Pull request merged**
