### PR TITLE
Proposal: add instructions fields for visually-impaired riders and clarify signposted_as in pathways.txt

### PR DESCRIPTION
**Pull request by scmcca**
**EDITS**
- 2021-01-28: Emphasized instructions for visually-impaired riders and made fields implicitly TTS compliant.

## Proposal

Routing passengers with [`pathways.txt`](http://gtfs.org/reference/static/#pathwaystxt) currently relies on connecting pairs of `stop_id` and following signage with `signposted_as` and `reverse_signposted_as`. While this works great for most cases, there are circumstances for which relying on in-station signage alone can be ambiguous for navigating complex in-station architecture; a particular concern for visually-impaired accessibility.

Following interest from NaviLens (as a consumer) and TMB Barcelona (as a producer) to make in-station routing more accessible for visually-impaired riders, this PR proposes to add two text fields to [`pathways.txt`](http://gtfs.org/reference/static/#pathwaystxt):

1. `visually_impaired_instructions` describes TTS readable step-by-step instructions for visually-impaired riders.
2. `reversed_visually_impaired_instructions` functions the same as `visually_impaired_instructions`, but when a pathway is taken in the opposite direction

Additionally, the descriptions of 2 fields have been updated in this PR to clarify their use (i.e. no changes have been made to the meaning of these fields):
1. `signposted_as` explicits the directionality (from `from_stop_id` to `to_stop_id`) and removes the ambiguity between providing text directions and appearing exactly like the signage
2. `reverse_signposted_as` minor changes for consistency

We ([MobilityData IO](https://mobilitydata.org/)) would love to hear if you or your affiliation are interested in producing or consuming these fields. This would give us an idea for which stakeholders to involve in the early-stages of specification drafting.

As always, don't hesitate to voice your needs or concerns on this PR. Thanks!

### CODE REVIEW

**Comment by skinkie** [comment]
I would love to hear who has made a producing workflow for this.

**Comment by NaviLens** [comment]
We strongly believe in a more inclusive transit for the visually-impaired and this evolution of the GTFS-Pathways can make a big difference for an independent journey when navigating through the stations.

At the same time is important to make something simple, easy to be created and maintain for the producers.

The main idea behind this proposal is to follow the current navigation instructions that GTFS-Pathways allows (combining the pathways + the field `signposted_as`), but filling the gap for the visually-impaired when the "Follow signs for ______ " instruction appears:


image


The blind users can not read the signs and follow them, so it's necessary to add some contextual information to help the user to reach its destination.

In this example at Bowdoin Station (Boston), after crossing the fare gate, the riders must turn left and go through a corridor to reach the area of the departing trains.

The sighted people can move smoothly following the signage indications(text + arrows) at the station, but these few meters are challenging for the visually-impaired.

The proposed `visually_impaired_instructions` could make a big difference. Only when necessary, will add the small extra information to achieve an independent journey in unknown stations for the visually-impaired.

`visually_impaired_instructions` **"Turn left and go down the corridor. The platform for departing trains is on the right"**


As simple as adding these few words can make a big difference for visually-impaired users.

---

Here are the images that illustrate the wayfinding challenge for this specific example 

(Please think that you can't see and you are using a white cane to move through this space)

1. Before the fare gate:


image


2. Just crossing the fare gate:


image


3. The user must turn left:


image


4. Go down the corridor:


image


5. At the end of the corridor the departing trains are on the right:


image

---


If this proposal is well received by the mobility community, imagine how can impact a few words to achieve independent travel for the visually-impaired.

Turn left and go down the corridor. The platform for departing trains is on the right

**Comment by NaviLens** [comment]
> How do (in this case the non existing) tactile lines fall in this proposal?

Hi Stefan,

Thank you for your question. 

Based on our experience, exactly in the same way. 

Indeed if the station would have tactile-paving the visually_impaired_instructions would be simpler and shorter, only describing the options of the "decision points" of the tactile paving (where the tactile-paving have several options in one particular point).

Adding the `visually_imapired_instructions` will be the solution to help the visually-impaired to know if they need to turn to the left or to the right in this graphical example.


image

**Comment by uwtcat** [comment]
Hi- In general, there is no question that there are tags missing in the pathways.txt and in particular as a mechanism to offer navigational tools for individuals who are Blind, low Vision or DeafBlind. 

However, as we have been working with the interested communities, we have found that the manner in which wheelchair accessible paths are described and the way orientation and mobility guidance is done through transit spaces for travelers in VI, Blind and Deafblind settings is quite a bit different, so much so that a simple 'overlay' of the relevant audio instruction set unto the centerline path through the station is likely not going to produce the results we want. 

As an example, O&M specialists, we are told, use additional waypoints (breadcrumbs, landmarks, they have different names) to demarcate the path, and have specific auditory messages to convey the next step in the path, conditioned on who the traveler is and what their destination in the station might be. The message will be specific to the waypoint (whether it's a card reader, a posterboard, or an information station), specific to where they are headed in the station, and specific to the traveler (i.e., whether the message will say "turn 45 degrees to your right and advance 30 feet to the <next waypoint>" or it will say "turn half right and take 45 steps to the <next waypoint>" will depend on traveler preferences and experience with auditory messages). 

What I'm saying is two-fold:
1) I think this discussion should be better informed: we need O&M specialists and consultation with the WayFndr guidance on auditory messages.
2) The community needs to agree that adding these tags  can and should be done in conjunction with increasing the granularity of pathways through the addition of "breadcrumb"/"generic_node" node types that are neither stop_id nor entrances.

Then maybe this would allow for more realistic auditory navigation through a station, and in particular, through some of the open spaces in stations which would require new nodes and new pathways that are not co-occurrent with the wheelchair-accessible pathways. 

As for surface and tactile information- I think we need a whole separate tag for that. It is much easier for digital data consumers to deal with data types that specifically enumerate the kind of surface to expect on the pathway (regardless of the pathway type). We should not have to parse through the auditory messages to discover if the path has a tactile surface. In fact, there are many different types of travelers who have vision, but would like to avoid tactile surfaces (people using canes, certain manual wheelchairs, people with high heels...). Hence, it does not make sense to me to embed tactility in the auditory messages.

I'm hoping to continue this discussion!

**Comment by NaviLens** [comment]
> Hi- In general, there is no question that there are tags missing in the pathways.txt and in particular as a mechanism to offer navigational tools for individuals who are Blind, low Vision or DeafBlind.
> 
> However, as we have been working with the interested communities, we have found that the manner in which wheelchair accessible paths are described and the way orientation and mobility guidance is done through transit spaces for travelers in VI, Blind and Deafblind settings is quite a bit different, so much so that a simple 'overlay' of the relevant audio instruction set unto the centerline path through the station is likely not going to produce the results we want.
> 
> As an example, O&M specialists, we are told, use additional waypoints (breadcrumbs, landmarks, they have different names) to demarcate the path, and have specific auditory messages to convey the next step in the path, conditioned on who the traveler is and what their destination in the station might be. The message will be specific to the waypoint (whether it's a card reader, a posterboard, or an information station), specific to where they are headed in the station, and specific to the traveler (i.e., whether the message will say "turn 45 degrees to your right and advance 30 feet to the " or it will say "turn half right and take 45 steps to the " will depend on traveler preferences and experience with auditory messages).
> 
> What I'm saying is two-fold:
> 
> 1. I think this discussion should be better informed: we need O&M specialists and consultation with the WayFndr guidance on auditory messages.
> 2. The community needs to agree that adding these tags  can and should be done in conjunction with increasing the granularity of pathways through the addition of "breadcrumb"/"generic_node" node types that are neither stop_id nor entrances.
> 
> Then maybe this would allow for more realistic auditory navigation through a station, and in particular, through some of the open spaces in stations, which would require new nodes and new pathways that are not co-occurrent with the wheelchair-accessible pathways.
> 
> As for surface and tactile information- I think we need a whole separate tag for that. It is much easier for digital data consumers to deal with data types that specifically enumerate the kind of surface to expect on the pathway (regardless of the pathway type). We should not have to parse through the auditory messages to discover if the path has a tactile surface. In fact, there are many different types of travelers who have vision but would like to avoid tactile surfaces (people using canes, certain manual wheelchairs, people with high heels...). Hence, it does not make sense to me to embed tactility in the auditory messages.
> 
> I'm hoping to continue this discussion!

Thank you very much for your comment!

Happy to have you in this conversation.

Yes, we absolutely agree. It's necessary to add some tags/information to help the visually-impaired users wayfinding through the station.

At the beginning of our work, we thought about creating separate files to achieve more detailed information for visually-impaired users (VI). The problem that we found is that those extra files meant a notable increase in complexity for producers.

In our opinion, the key point is to have the more stations possible with helpful instructions for the visually-impaired to help them to navigate independently, filling the gap that the current GTFS files have. (We have exposed the problem from a visually-impaired user in our first comment in this PR).

The way to achieve the goal of more and more stations with information for the visually-impaired is to balance the positive benefits for the users versus the costs of creating the data by the producers.

Of course, the priority is always the best for the visually-impaired users **is the most important for us**, but looking for a solution that the producers could manage **to incentivize them to add this information** and achieve the objective, that is to help the VI users.

If the proposal is complex/difficult to create or maintain, it would be a barrier to produce this information.

In the real example of Boston that we put in the first post of this PR, you can see that adding a piece of simple extra information into the GTFS-Pathways achieves a significant positive difference for independent travel for the VI users.

In most stations, those referenced waypoints that the visually-impaired users use (breadcrumbs, landmarks) could be the physical elements of the pathways themselves (entrance, stairs, fare gates, elevators, etc.). In those cases, a minimal amount of information from the producer could make a real positive difference for the VI users navigation through the station.

And yes, we agree, the good thing about the approximation of this PR is that in the case of complex spaces, the solution to achieve a better information/experience for the visually-impaired users is adding more granularity to the pathways.txt, not only to help the visually-impaired itself but also to help all the riders (sighted people as well) when the space from the start to the end of the pathway is huge. 

In complex spaces, sometimes "follow signs for" could be challenging for everyone, not only the VI users, so increasing the granularity will help everyone. Everyone wins.

This is a proposition; for us, the more information available, the better. Better for the users, and better for the experience that we could bring to the users. But the important thing is to have something available, something that could help the users.

Happy to see any specific suggestion or an alternative proposal to achieve the objective of helping the users, incentivizing producers to add valuable information for the visually-impaired about the physical space at the most number of stations.

The important point is to achieve a solution that the producers could easily create, easily integrated by consumers Apps to help more and more visually impaired users.

:)

**Comment by accessibilitattmb** [comment]
We (TMB Transports Metropolitans of Barcelona) are committed to the inclusion of the visually-impaired users in our transport network.

We are applying this methodology to make our stations more accessible for visually-impaired people.

Very soon we will publish the GTFS-Pathways content of our pilot station where we are applying this new methodology, including the visually_impaired_instructions information, to show the community how we are implementing it.

**Comment by tmbaccessibilitat** [comment]
We (TMB Transports Metropolitans of Barcelona) are committed to the inclusion of the visually-impaired users in our transport network.

We are applying this methodology to make our stations more accessible for visually-impaired people.

A first dataset with the GTFS-Pathways content of our pilot station where we are applying this new methodology, including the visually_impaired_instructions information has been created for Fira Station to show the community how we are implementing. 

It's publicly available for those who want to see what it looks like: http://bit.ly/3k5Gjpm

**Comment by NaviLens** [comment]
Good news from NaviLens!

Following the data published by @tmbaccessibilitat, which includes the new `visually_impaired_instructions` field we already have integrated this new GTFS-Pathways information generated by TMB into our consumer App. 

When a NaviLens user reads a code in the Fira Station with our application, the content of the `visually_impaired_instructions` and `reversed_visually_impaired_instructions` fields of the dataset provided by TMB are displayed.

Below you can see an example of what is displayed in the App with the new fields:

NaviLens App Capture1

NaviLens App Capture2

We are very delighted to have this new data to help the visually-impaired riders when navigating through the station!

Thank you all for making it possible!

**Comment by scmcca** [comment]
With @tmbaccessibilitat as producer and @NaviLens as a consumer, we can call a vote! 

This vote is for the official adoption of `pathways.visually_impaired_instructions` and `pathways.reversed_visually_impaired_instructions` as described in this PR.

**The vote will close on 2021-03-25 at 23:59:59 UTC.**

**Comment by tmbaccessibilitat** [comment]
+1

**Comment by uwtcat** [comment]
-1 (downvote)
I'm very sorry. I'm a huge proponent of adding instructions for visually impaired individuals, but with the current field, this is totally under-specified and I am concerned about situations in which data producers will create instructions that are not helpful (or even harmful) for people with no or low vision, while still being completely conforming to the standard (and also "passing" any kind of digital validation or review). I believe we can do better in terms of offering subfields in pathways.txt that provide a more structured, guided way for pathways producers to do the right thing and offer truly helpful auditory indicators for people with disabilities. To summarize: there is no question that this is an issue that needs to be addressed in pathways and we fully appreciate the partnership between TMB and NaviLens in promoting awareness of this issue, but the current proposed subfields are not helpful in addressing this in a consistent, standardized way.

**Comment by skinkie** [comment]
@uwtcat thanks for expressing this so well.

-1

**Comment by e-lo** [comment]
@uwtcat - do you have an alternate proposal we should be considering alongside?

**Comment by uwtcat** [comment]
Hi again, well, yes, I do. Should we start a new issue on this? I don't want to adultrate this one, and also allow the rest of the community to vote on this. I will put in my list below, but maybe ought to start a new issue for a vote later on. 

Mainly- we at the Taskar Center and AccessMap believe pathways.txt should be a graph-driven standard, where stop_id still describe the nodes on the paths, but a clear description of the edges connecting these nodes are currently missing. If the standard requires producers to define descriptive tags, for both the nodes (the stop_id's) and the edges (the paths between the nodes), then this is a way to guide the data collection process as well as guide good auditory descriptions of the route through the station.

In addition to the edge descriptions, I believe the current pathways is missing descriptor fields that every station should have like an Origin Point and a Frame of Reference for the space that is being described by pathways, which can later serve as reference for the pathways.

Below are tags I believe should be part of pathways to displace the proposed visually_impaired_instructions tags. These were informed by literature and our own studies with Lighthouse for the Blind (primarily David Miller, an exemplar O&M specialist) and a community of 24 DeafBlind participants through the DeafBlind Service Center in Seattle, WA. This may not be an exhaustive list, but one that we believe is a good start.

For the paths between stop_ids (these can be separately described in the forward and backward manner if the community chooses to do this, but I don't believe it should be necessary to do that given the tagging):
forward_link_absolute_turn_direction (this is the cardinal direction of this next link)
forward_link_relative_turn_degrees (this is the turn description relative to the inbound previous link on this forward path, example: 145 degree turn to the right. Standard would state which direction is assumed)
reverse_link_absolute_turn_direction (absolute dir of the outpath in reverse direction)
reverse_link_relative_turn_degrees 
forward_link_absolute_length (in a measured unit, not steps, although many users could express a preference for having the audible messages translate this length to their number of steps. That would be done by the application, not in the standard)
reverse_link_absolute_length
link_elevation_change
link_tactile_paving (either bool or enumerated description of the type of tactile surface)
forward_link_edge_right (describes what is adjacent to this path on right)
forward_link_edge_left (describes what is adjacent to this path on left)
link_surface_material
link_surface_evenness
link_surface_traction
link_width
link_cross_slope
link_open_space (bool)
link_one_way  (bool)
link_two_way (bool)
link_multi_way  (bool)
link_lighting (distance to the nearest light source rather than some subjective lighting condition)
link_overhang 
link_Underpass  (bool)
link_Overpass (bool)
link_stairs  (bool) (I realize this duplicates something already sort of in pathways.txt)
link_stairs_number_of_steps (int)
link_handrails  (bool)
link_raised  (bool)
Some tags to describe point-specific objects along the link like,Obstacles,Landmarks/tactile features/street furniture although these point objects should likely be described as stops in pathways.txt rather than just points on the links.

I get that this seems like nauseating detail, but most of these tags are booleans and really offer the kind of guidance to data producers that would go completely unchecked otherwise. 

I look forward to reading your comments.

**Comment by skinkie** [comment]
@uwtcat would love to discuss this interactively. Can we plan a meeting or something?

**Comment by scmcca** [comment]
@uwtcat Thanks for the detailed and constructive feedback! 

I think the community would benefit from an informed conversation. I agree that opening a separate issue to centralize the conversation seems appropriate! In that issue, it would be great if you could link to your mentioned literature review and research materials, and a working google doc containing your proposals as described above (or you can add suggestions to the existing [GTFS-Pathways](https://docs.google.com/document/d/1qJOTe4m_a4dcJnvXYt4smYj4QQ1ejZ8CvLBYzDM5IyM/edit#heading=h.edxt3s6om1lm) working doc, whatever you think is most effective). You may also want to open a PR if or when you feel your proposal is ready.

Also, you are more than welcome to leverage the #gtfs-pathways or #gtfs_accessibility channels on the [MobilityData Slack](https://mobilitydata-io.herokuapp.com/) to tap into the community and work through solutions.

While the vote on this PR has failed, I will wait for the voting period to close in case there is more feedback. Nonetheless, I want to applaud @tmbaccessibilitat and @NaviLens for being proactive in providing VI navigation in GTFS and advancing the discussion in the community! 

I'm looking forward to a continued conversation. MobilityData is here to help and facilitate.

**Comment by NaviLens** [comment]
+1 from NaviLens

Happy to hear another realistic alternative proposal in order to be able to evaluate it. 

For us, the most important thing is to help the visually-impaired users.

Thanks for all the comments and special thanks to @tmbaccessibilitat and the great MobilityData.Org team!

**Comment by scmcca** [comment]
The vote ended on 2021-03-25 at 23:59:59 UTC. 

The results are 2 in favor (@tmbaccessibilitat and @NaviLens), and 2 (@uwtcat and @skinkie) opposed. 

As per the [specification amendment process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md), the vote did not pass.

To reiterate above, I heavily encourage a continuation of this work! 

Thanks to all involved :)

**Pull request closed without merging**
