### PR TITLE
Proposal: Introduce direction names to GTFS

### PR DESCRIPTION
**Pull request by dudebrains01**
Hello GTFS community!

Brody here coming to you from MobilityData with a proposal for direction names in GTFS.

This PR is related to issue #228.
## Context
Currently, the GTFS specification only provides the `trips.trip_headsign` and `stop_times.stop_headsign` field to provide information on the direction of a trip. However, the value in these fields is sometimes superseded by another name like "eastbound" or "inbound", to indicate the general direction of travel.

## Proposal

This proposal would introduce the concept of direction names to GTFS, to allow more general wayfinding instructions to be added to GTFS.

### Features
- New `direction_names.txt` file;
- New `trips.direction_name_id` field;
- New `stop_times.direction_name_id` field

## Producers and consumers
We are actively working with producers and consumers and should have a producer and consumer in the next few weeks.
If you are producing or consuming the extensions in this PR, please let us know in the comments.

### CODE REVIEW

**Comment by dudebrains01** [comment]
@googlebot I signed it!

**Comment by scmcca** [comment]
@googlebot I consent.

**Comment by skinkie** [comment]
This is not the result of the discussion.

**Comment by stevenmwhite** [comment]
@skinkie It sounds like you're fairly adamantly against Option D, which is this essentially the one in the PR, but would be ok with Option A.
Is anyone adamantly against Option A and for this option instead? I didn't particularly see that in the previous discussion

I'm going to give this a +1 for us, but I would gladly also give Option A a positive vote.

**Comment by sam-hickey-ibigroup** [comment]
For IBI:  We're happy this is moving forward. but we think this proposal has moved forward prior to consensus being reached in the previous discussion at [Issue 228](https://github.com/google/transit/issues/228).
 
We think that it is premature to open a proposal for this, since 1) the discussion of Options was still ongoing and it makes it more challenging if discussions are split across multiple issues/PRs, and 2) the proposal is based on Option D with some modifications, but the modifications were not discussed. For example: this line in the pull request "The same `trips.direction_name_id` must be provided per combination of `route_id` and `direction_id`." was not in Option D in the Google Doc linked at Issue 228. Also, more details were added in the definition of the direction_names.txt file that were not in the Google Doc linked at Issue 228.
 
That said, although we might be ok with this proposal going ahead as written, our concern is that there were still discussions ongoing at Issue 228 that have not be completed.

**Comment by timMillet** [comment]
This PR seems too early regarding the fact that options were still discussed in issue #228. Sorry about that.
I'm closing this PR, and we will open a new one when a consensus on one of the options presented in issue #228 will be reached.

Thank you, Stefan, Steve, and Sam for your feedback on this PR.

**Pull request closed without merging**
